energies = dict()

energies[81]  =  -3.17    # Ammoniadimer.xyz
energies[82]  =  -5.02    # Waterdimer.xyz
energies[83]  =  -1.50    # BenzeneMethanecomplex.xyz
energies[84]  = -18.61    # Formicaciddimer.xyz
energies[85]  = -15.96    # Formamidedimer.xyz
energies[86]  = -20.65    # Uracildimerhbonded.xyz
energies[87]  = -16.71    # 2pyridoxine2aminopyridinecomplex.xyz
energies[88]  = -16.37    # AdeninethymineWatsonCrickcomplex.xyz
energies[89]  =  -0.53    # Methanedimer.xyz
energies[90]  =  -1.51    # Ethenedimer.xyz
energies[91]  =  -2.73    # Benzenedimerparalleldisplaced.xyz
energies[92]  =  -4.42    # Pyrazinedimer.xyz
energies[93]  = -10.12    # Uracildimerstack.xyz
energies[94]  =  -5.22    # Indolebenzenecomplexstack.xyz
energies[95]  = -12.23    # Adeninethyminecomplexstack.xyz
energies[96]  =  -1.53    # Etheneethynecomplex.xyz
energies[97]  =  -3.28    # Benzenewatercomplex.xyz
energies[98]  =  -2.35    # Benzeneammoniacomplex.xyz
energies[99]  =  -4.46    # BenzeneHCNcomplex.xyz
energies[100] =  -2.74    # BenzenedimerTshaped.xyz
energies[101] =  -5.73    # IndolebenzeneTshapecomplex.xyz
energies[102] =  -7.05    # Phenoldimer.xyz

names = dict()

names[81]  = "Ammoniadimer.xyz"
names[82]  = "Waterdimer.xyz"
names[83]  = "BenzeneMethanecomplex.xyz"
names[84]  = "Formicaciddimer.xyz"
names[85]  = "Formamidedimer.xyz"
names[86]  = "Uracildimerhbonded.xyz"
names[87]  = "2pyridoxine2aminopyridinecomplex.xyz"
names[88]  = "AdeninethymineWatsonCrickcomplex.xyz"
names[89]  = "Methanedimer.xyz"
names[90]  = "Ethenedimer.xyz"
names[91]  = "Benzenedimerparalleldisplaced.xyz"
names[92]  = "Pyrazinedimer.xyz"
names[93]  = "Uracildimerstack.xyz"
names[94]  = "Indolebenzenecomplexstack.xyz"
names[95]  = "Adeninethyminecomplexstack.xyz"
names[96]  = "Etheneethynecomplex.xyz"
names[97]  = "Benzenewatercomplex.xyz"
names[98]  = "Benzeneammoniacomplex.xyz"
names[99]  = "BenzeneHCNcomplex.xyz"
names[100] = "BenzenedimerTshaped.xyz"
names[101] = "IndolebenzeneTshapecomplex.xyz"
names[102] = "Phenoldimer.xyz"
